### ISSUE TITLE
有的链接打不开！

### ISSUE THREAD

**Issue by liuhaimingcn** [justjavac/what-happens-when-zh_CN#2]
当你开启电脑时，它发生了什么
for 循环中到底发生了什么—— Python 提高班

这俩问题的链接不能用了！

**Comment by shipengtaov** [comment]
https://web.archive.org/web/*/http://www.linuxsir.org/bbs/thread205849.html
[for循环中到底发生了什么--Python提高班](http://segmentfault.com/a/1190000000493276)
